image:
  - Visual Studio 2017

environment:
  ModuleName: "Write-Day"
  Author: "Tom Bonner"
  Description: "Writes the day to output"
  ProjectUri: "https://github.com/Glitch0011/PowershellGalleryExperiment"
  LicenseUri: "https://github.com/Glitch0011/PowershellGalleryExperiment/blob/master/LICENSE"
  FunctionsToExport: "Write-Day"
  Tags: "Date;Write"
  NuGetApiKey:
    secure: vPuoV+7e5qgXDOi6iZOMgOGQDiA2H5rOvVaGO13SvePSehwTGHHE4W3hSPTlu0zL

skip_tags: true

pull_requests:
  do_not_increment_build_number: true

init:
  - ps: Update-AppveyorBuild -Version "$(Get-Date -Format yy.MM.dd).$($Env:APPVEYOR_BUILD_NUMBER)"
  
build_script:
  - ps: .\Generate-Module.ps1

test_script:
  - ps: |
      $res = Invoke-Pester -Path ".\tests" -OutputFormat "NUnitXml" -OutputFile "TestsResults.xml" -PassThru
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
      if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}

artifacts:
  - path: '**\*.nupkg'

deploy:
  - provider: NuGet
    server: "https://www.powershellgallery.com/api/v2/package/"
    api_key:
      secure: vPuoV+7e5qgXDOi6iZOMgOGQDiA2H5rOvVaGO13SvePSehwTGHHE4W3hSPTlu0zL
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: master

  - provider: GitHub
    description: ""
    auth_token:
      secure: 18s9Uox34x4O+jldUgWcT8CBaSeKDj5yZ0tqsE3/YqaU3qODoVzGoSkvmU1l2oF9
    artifact: /.*\.nupkg/
    on:
      branch: master

notifications:
  - provider: Webhook
    url:
      secure: 7ZT0ZVyDmNP7553URWST6RsaqDKHJQ9gKXmn9e6Vam8=