image:
  - Visual Studio 2017

environment:
  NuGetApiKey:
    secure: vPuoV+7e5qgXDOi6iZOMgOGQDiA2H5rOvVaGO13SvePSehwTGHHE4W3hSPTlu0zL

build_script:
  - ps: .\Generate-Module.ps1

test_script:
  - ps: |
      Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
      $results = Invoke-ScriptAnalyzer (Get-Item ".\src\*.psm1").FullName
      if ($results.length -gt 0) {
        throw "Script validation failed"
      }

artifacts:
  - path: '**\*.nupkg'

deploy_script:
  - ps: Publish-Module -Name (Get-Item ".\src\*.psd1").FullName -NuGetApiKey $Env:NuGetApiKey

after_deploy:
  - ps: Write-Host "Successfully deployed"

notifications:
  - provider: Webhook
    url:
      secure: 7ZT0ZVyDmNP7553URWST6RsaqDKHJQ9gKXmn9e6Vam8=