image:
  - Visual Studio 2017

install:
  - ps: Write-Host "Startup"

build_script:
  -  ps: .\Generate-Module.ps1  

artifacts:
  - path: deploy

deploy:
  - provider: NuGet
    server: https://www.powershellgallery.com/api/v2/
    api_key:
      secure: vPuoV+7e5qgXDOi6iZOMgOGQDiA2H5rOvVaGO13SvePSehwTGHHE4W3hSPTlu0zL
    skip_symbols: true
    artifact: /.*\.nupkg/

after_deploy:
  - ps: Write-Host "Successfully deployed"

notifications:
  - provider: Email
    to:
      - tom+appveyor@bonner.is
    subject: "Build {{status}}"
    message: "{{message}}"
    on_build_status_changed: true

  - provider: Webhook
    url:
      secure: 7ZT0ZVyDmNP7553URWST6Xz9+oHCE6WTRDPTqw1rvh8=