image:
  - Visual Studio 2017

deploy: off

for:
  branches:
    only:
      - master
  deploy: on

environment:
  ModuleName: "Write-Day"
  Author: "Tom Bonner"
  Description: "Writes the day to output"
  ProjectUri: "https://github.com/Glitch0011/PowershellGalleryExperiment"
  LicenseUri: "https://github.com/Glitch0011/PowershellGalleryExperiment/blob/master/LICENSE"
  FunctionsToExport: "Write-Day"
  Tags: "Date;Write"
  NuGetApiKey:
    secure: vPuoV+7e5qgXDOi6iZOMgOGQDiA2H5rOvVaGO13SvePSehwTGHHE4W3hSPTlu0zL
  
init:
  - ps: Update-AppveyorBuild -Version "$(Get-Date -Format yy.MM.dd).$($Env:APPVEYOR_BUILD_NUMBER)"
  
build_script:
  - ps: .\Generate-Module.ps1

test_script:
  - ps: |
      $results = Invoke-ScriptAnalyzer (Get-Item ".\src\*.psm1").FullName
      if ($results.length -gt 0) {
        throw "Script validation failed"
      }

artifacts:
  - path: '**\*.nupkg'

deploy_script:
  - ps: Publish-Module -Name (Get-Item ".\staging\*.psd1").FullName -NuGetApiKey $Env:NuGetApiKey

after_deploy:
  - ps: Write-Host "Successfully deployed"

notifications:
  - provider: Webhook
    url:
      secure: 7ZT0ZVyDmNP7553URWST6RsaqDKHJQ9gKXmn9e6Vam8=